/*
 * This file is generated by jOOQ.
 */
package place.sita.labelle.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import place.sita.labelle.jooq.Keys;
import place.sita.labelle.jooq.Public;
import place.sita.labelle.jooq.tables.records.MarkerRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Marker extends TableImpl<MarkerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.marker</code>
     */
    public static final Marker MARKER = new Marker();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MarkerRecord> getRecordType() {
        return MarkerRecord.class;
    }

    /**
     * The column <code>public.marker.image_id</code>.
     */
    public final TableField<MarkerRecord, UUID> IMAGE_ID = createField(DSL.name("image_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.marker.category</code>.
     */
    public final TableField<MarkerRecord, String> CATEGORY = createField(DSL.name("category"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.marker.value</code>.
     */
    public final TableField<MarkerRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.marker.shared</code>.
     */
    public final TableField<MarkerRecord, Boolean> SHARED = createField(DSL.name("shared"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private Marker(Name alias, Table<MarkerRecord> aliased) {
        this(alias, aliased, null);
    }

    private Marker(Name alias, Table<MarkerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.marker</code> table reference
     */
    public Marker(String alias) {
        this(DSL.name(alias), MARKER);
    }

    /**
     * Create an aliased <code>public.marker</code> table reference
     */
    public Marker(Name alias) {
        this(alias, MARKER);
    }

    /**
     * Create a <code>public.marker</code> table reference
     */
    public Marker() {
        this(DSL.name("marker"), null);
    }

    public <O extends Record> Marker(Table<O> child, ForeignKey<O, MarkerRecord> key) {
        super(child, key, MARKER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<MarkerRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MARKER__MARKER_IMAGE_ID);
    }

    private transient Image _image;

    public Image image() {
        if (_image == null)
            _image = new Image(this, Keys.MARKER__MARKER_IMAGE_ID);

        return _image;
    }

    @Override
    public Marker as(String alias) {
        return new Marker(DSL.name(alias), this);
    }

    @Override
    public Marker as(Name alias) {
        return new Marker(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Marker rename(String name) {
        return new Marker(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Marker rename(Name name) {
        return new Marker(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, String, String, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
