/*
 * This file is generated by jOOQ.
 */
package place.sita.labelle.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import place.sita.labelle.jooq.Keys;
import place.sita.labelle.jooq.Public;
import place.sita.labelle.jooq.tables.records.TagDeltaRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagDelta extends TableImpl<TagDeltaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tag_delta</code>
     */
    public static final TagDelta TAG_DELTA = new TagDelta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TagDeltaRecord> getRecordType() {
        return TagDeltaRecord.class;
    }

    /**
     * The column <code>public.tag_delta.image_id</code>.
     */
    public final TableField<TagDeltaRecord, UUID> IMAGE_ID = createField(DSL.name("image_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.tag_delta.adds</code>.
     */
    public final TableField<TagDeltaRecord, Boolean> ADDS = createField(DSL.name("adds"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.tag_delta.family</code>.
     */
    public final TableField<TagDeltaRecord, String> FAMILY = createField(DSL.name("family"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.tag_delta.tag</code>.
     */
    public final TableField<TagDeltaRecord, String> TAG = createField(DSL.name("tag"), SQLDataType.CLOB.nullable(false), this, "");

    private TagDelta(Name alias, Table<TagDeltaRecord> aliased) {
        this(alias, aliased, null);
    }

    private TagDelta(Name alias, Table<TagDeltaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.tag_delta</code> table reference
     */
    public TagDelta(String alias) {
        this(DSL.name(alias), TAG_DELTA);
    }

    /**
     * Create an aliased <code>public.tag_delta</code> table reference
     */
    public TagDelta(Name alias) {
        this(alias, TAG_DELTA);
    }

    /**
     * Create a <code>public.tag_delta</code> table reference
     */
    public TagDelta() {
        this(DSL.name("tag_delta"), null);
    }

    public <O extends Record> TagDelta(Table<O> child, ForeignKey<O, TagDeltaRecord> key) {
        super(child, key, TAG_DELTA);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<TagDeltaRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TAG_DELTA__FK_IMAGE_DELTA_IMAGE_ID);
    }

    private transient Image _image;

    public Image image() {
        if (_image == null)
            _image = new Image(this, Keys.TAG_DELTA__FK_IMAGE_DELTA_IMAGE_ID);

        return _image;
    }

    @Override
    public TagDelta as(String alias) {
        return new TagDelta(DSL.name(alias), this);
    }

    @Override
    public TagDelta as(Name alias) {
        return new TagDelta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TagDelta rename(String name) {
        return new TagDelta(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TagDelta rename(Name name) {
        return new TagDelta(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, Boolean, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
