/*
 * This file is generated by jOOQ.
 */
package place.sita.labelle.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import place.sita.labelle.jooq.Keys;
import place.sita.labelle.jooq.Public;
import place.sita.labelle.jooq.tables.records.TaskConfigRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskConfig extends TableImpl<TaskConfigRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.task_config</code>
     */
    public static final TaskConfig TASK_CONFIG = new TaskConfig();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TaskConfigRecord> getRecordType() {
        return TaskConfigRecord.class;
    }

    /**
     * The column <code>public.task_config.task_id</code>.
     */
    public final TableField<TaskConfigRecord, UUID> TASK_ID = createField(DSL.name("task_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.task_config.config</code>.
     */
    public final TableField<TaskConfigRecord, String> CONFIG = createField(DSL.name("config"), SQLDataType.CLOB, this, "");

    private TaskConfig(Name alias, Table<TaskConfigRecord> aliased) {
        this(alias, aliased, null);
    }

    private TaskConfig(Name alias, Table<TaskConfigRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.task_config</code> table reference
     */
    public TaskConfig(String alias) {
        this(DSL.name(alias), TASK_CONFIG);
    }

    /**
     * Create an aliased <code>public.task_config</code> table reference
     */
    public TaskConfig(Name alias) {
        this(alias, TASK_CONFIG);
    }

    /**
     * Create a <code>public.task_config</code> table reference
     */
    public TaskConfig() {
        this(DSL.name("task_config"), null);
    }

    public <O extends Record> TaskConfig(Table<O> child, ForeignKey<O, TaskConfigRecord> key) {
        super(child, key, TASK_CONFIG);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TaskConfigRecord> getPrimaryKey() {
        return Keys.TASK_CONFIG_PKEY;
    }

    @Override
    public List<ForeignKey<TaskConfigRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TASK_CONFIG__FK_TASK_CONFIG_TASK_ID);
    }

    private transient Task _task;

    public Task task() {
        if (_task == null)
            _task = new Task(this, Keys.TASK_CONFIG__FK_TASK_CONFIG_TASK_ID);

        return _task;
    }

    @Override
    public TaskConfig as(String alias) {
        return new TaskConfig(DSL.name(alias), this);
    }

    @Override
    public TaskConfig as(Name alias) {
        return new TaskConfig(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskConfig rename(String name) {
        return new TaskConfig(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskConfig rename(Name name) {
        return new TaskConfig(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
