/*
 * This file is generated by jOOQ.
 */
package place.sita.labelle.jooq.tables;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import place.sita.labelle.jooq.Keys;
import place.sita.labelle.jooq.Public;
import place.sita.labelle.jooq.tables.records.TaskTypeRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskType extends TableImpl<TaskTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.task_type</code>
     */
    public static final TaskType TASK_TYPE = new TaskType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TaskTypeRecord> getRecordType() {
        return TaskTypeRecord.class;
    }

    /**
     * The column <code>public.task_type.id</code>.
     */
    public final TableField<TaskTypeRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.task_type.code</code>.
     */
    public final TableField<TaskTypeRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.task_type.name</code>.
     */
    public final TableField<TaskTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    private TaskType(Name alias, Table<TaskTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TaskType(Name alias, Table<TaskTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.task_type</code> table reference
     */
    public TaskType(String alias) {
        this(DSL.name(alias), TASK_TYPE);
    }

    /**
     * Create an aliased <code>public.task_type</code> table reference
     */
    public TaskType(Name alias) {
        this(alias, TASK_TYPE);
    }

    /**
     * Create a <code>public.task_type</code> table reference
     */
    public TaskType() {
        this(DSL.name("task_type"), null);
    }

    public <O extends Record> TaskType(Table<O> child, ForeignKey<O, TaskTypeRecord> key) {
        super(child, key, TASK_TYPE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TaskTypeRecord> getPrimaryKey() {
        return Keys.TASK_TYPE_PKEY;
    }

    @Override
    public TaskType as(String alias) {
        return new TaskType(DSL.name(alias), this);
    }

    @Override
    public TaskType as(Name alias) {
        return new TaskType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskType rename(String name) {
        return new TaskType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskType rename(Name name) {
        return new TaskType(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
