databaseChangeLog:
  - changeSet:
      id: 0015-01
      author: kamil-sita
      changes:
        - addColumn:
            tableName: task_execution
            columns:
              - column:
                  name: configuration
                  type: text
                  constraints:
                    nullable: true