/*
 * This file is generated by jOOQ.
 */
package place.sita.labelle.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;

import place.sita.labelle.jooq.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum TaskExecutionResult implements EnumType {

    DONE("DONE"),

    DUPLICATE("DUPLICATE"),

    SOFT_FAIL("SOFT_FAIL"),

    HARD_FAIL("HARD_FAIL");

    private final String literal;

    private TaskExecutionResult(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "task_execution_result";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
