/*
 * This file is generated by jOOQ.
 */
package place.sita.labelle.jooq.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import place.sita.labelle.jooq.tables.Image;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImageRecord extends UpdatableRecordImpl<ImageRecord> implements Record4<UUID, UUID, UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.image.image_resolvable_id</code>.
     */
    public void setImageResolvableId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.image.image_resolvable_id</code>.
     */
    public UUID getImageResolvableId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.image.repository_id</code>.
     */
    public void setRepositoryId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.image.repository_id</code>.
     */
    public UUID getRepositoryId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.image.id</code>.
     */
    public void setId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.image.id</code>.
     */
    public UUID getId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.image.parent_id</code>.
     */
    public void setParentId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.image.parent_id</code>.
     */
    public UUID getParentId() {
        return (UUID) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, UUID, UUID, UUID> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UUID, UUID, UUID, UUID> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Image.IMAGE.IMAGE_RESOLVABLE_ID;
    }

    @Override
    public Field<UUID> field2() {
        return Image.IMAGE.REPOSITORY_ID;
    }

    @Override
    public Field<UUID> field3() {
        return Image.IMAGE.ID;
    }

    @Override
    public Field<UUID> field4() {
        return Image.IMAGE.PARENT_ID;
    }

    @Override
    public UUID component1() {
        return getImageResolvableId();
    }

    @Override
    public UUID component2() {
        return getRepositoryId();
    }

    @Override
    public UUID component3() {
        return getId();
    }

    @Override
    public UUID component4() {
        return getParentId();
    }

    @Override
    public UUID value1() {
        return getImageResolvableId();
    }

    @Override
    public UUID value2() {
        return getRepositoryId();
    }

    @Override
    public UUID value3() {
        return getId();
    }

    @Override
    public UUID value4() {
        return getParentId();
    }

    @Override
    public ImageRecord value1(UUID value) {
        setImageResolvableId(value);
        return this;
    }

    @Override
    public ImageRecord value2(UUID value) {
        setRepositoryId(value);
        return this;
    }

    @Override
    public ImageRecord value3(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ImageRecord value4(UUID value) {
        setParentId(value);
        return this;
    }

    @Override
    public ImageRecord values(UUID value1, UUID value2, UUID value3, UUID value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImageRecord
     */
    public ImageRecord() {
        super(Image.IMAGE);
    }

    /**
     * Create a detached, initialised ImageRecord
     */
    public ImageRecord(UUID imageResolvableId, UUID repositoryId, UUID id, UUID parentId) {
        super(Image.IMAGE);

        setImageResolvableId(imageResolvableId);
        setRepositoryId(repositoryId);
        setId(id);
        setParentId(parentId);
    }
}
