/*
 * This file is generated by jOOQ.
 */
package place.sita.labelle.jooq.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import place.sita.labelle.jooq.tables.ImageFile;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImageFileRecord extends UpdatableRecordImpl<ImageFileRecord> implements Record3<UUID, UUID, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.image_file.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.image_file.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.image_file.root_id</code>.
     */
    public void setRootId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.image_file.root_id</code>.
     */
    public UUID getRootId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.image_file.relative_dir</code>.
     */
    public void setRelativeDir(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.image_file.relative_dir</code>.
     */
    public String getRelativeDir() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, UUID, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return ImageFile.IMAGE_FILE.ID;
    }

    @Override
    public Field<UUID> field2() {
        return ImageFile.IMAGE_FILE.ROOT_ID;
    }

    @Override
    public Field<String> field3() {
        return ImageFile.IMAGE_FILE.RELATIVE_DIR;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getRootId();
    }

    @Override
    public String component3() {
        return getRelativeDir();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getRootId();
    }

    @Override
    public String value3() {
        return getRelativeDir();
    }

    @Override
    public ImageFileRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ImageFileRecord value2(UUID value) {
        setRootId(value);
        return this;
    }

    @Override
    public ImageFileRecord value3(String value) {
        setRelativeDir(value);
        return this;
    }

    @Override
    public ImageFileRecord values(UUID value1, UUID value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImageFileRecord
     */
    public ImageFileRecord() {
        super(ImageFile.IMAGE_FILE);
    }

    /**
     * Create a detached, initialised ImageFileRecord
     */
    public ImageFileRecord(UUID id, UUID rootId, String relativeDir) {
        super(ImageFile.IMAGE_FILE);

        setId(id);
        setRootId(rootId);
        setRelativeDir(relativeDir);
    }
}
