/*
 * This file is generated by jOOQ.
 */
package place.sita.labelle.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import place.sita.labelle.jooq.tables.Preferences;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PreferencesRecord extends UpdatableRecordImpl<PreferencesRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.preferences.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.preferences.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.preferences.value</code>.
     */
    public void setValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.preferences.value</code>.
     */
    public String getValue() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Preferences.PREFERENCES.NAME;
    }

    @Override
    public Field<String> field2() {
        return Preferences.PREFERENCES.VALUE;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public String component2() {
        return getValue();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public String value2() {
        return getValue();
    }

    @Override
    public PreferencesRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public PreferencesRecord value2(String value) {
        setValue(value);
        return this;
    }

    @Override
    public PreferencesRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PreferencesRecord
     */
    public PreferencesRecord() {
        super(Preferences.PREFERENCES);
    }

    /**
     * Create a detached, initialised PreferencesRecord
     */
    public PreferencesRecord(String name, String value) {
        super(Preferences.PREFERENCES);

        setName(name);
        setValue(value);
    }
}
