/*
 * This file is generated by jOOQ.
 */
package place.sita.labelle.jooq.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import place.sita.labelle.jooq.tables.Root;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RootRecord extends UpdatableRecordImpl<RootRecord> implements Record2<UUID, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.root.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.root.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.root.root_dir</code>.
     */
    public void setRootDir(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.root.root_dir</code>.
     */
    public String getRootDir() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Root.ROOT.ID;
    }

    @Override
    public Field<String> field2() {
        return Root.ROOT.ROOT_DIR;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getRootDir();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getRootDir();
    }

    @Override
    public RootRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public RootRecord value2(String value) {
        setRootDir(value);
        return this;
    }

    @Override
    public RootRecord values(UUID value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RootRecord
     */
    public RootRecord() {
        super(Root.ROOT);
    }

    /**
     * Create a detached, initialised RootRecord
     */
    public RootRecord(UUID id, String rootDir) {
        super(Root.ROOT);

        setId(id);
        setRootDir(rootDir);
    }
}
