/*
 * This file is generated by jOOQ.
 */
package place.sita.labelle.jooq.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import place.sita.labelle.jooq.tables.Tag;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagRecord extends UpdatableRecordImpl<TagRecord> implements Record3<String, UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tag.value</code>.
     */
    public void setValue(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tag.value</code>.
     */
    public String getValue() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.tag.id</code>.
     */
    public void setId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tag.id</code>.
     */
    public UUID getId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.tag.tag_src_id</code>.
     */
    public void setTagSrcId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tag.tag_src_id</code>.
     */
    public UUID getTagSrcId() {
        return (UUID) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, UUID, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, UUID, UUID> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Tag.TAG.VALUE;
    }

    @Override
    public Field<UUID> field2() {
        return Tag.TAG.ID;
    }

    @Override
    public Field<UUID> field3() {
        return Tag.TAG.TAG_SRC_ID;
    }

    @Override
    public String component1() {
        return getValue();
    }

    @Override
    public UUID component2() {
        return getId();
    }

    @Override
    public UUID component3() {
        return getTagSrcId();
    }

    @Override
    public String value1() {
        return getValue();
    }

    @Override
    public UUID value2() {
        return getId();
    }

    @Override
    public UUID value3() {
        return getTagSrcId();
    }

    @Override
    public TagRecord value1(String value) {
        setValue(value);
        return this;
    }

    @Override
    public TagRecord value2(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public TagRecord value3(UUID value) {
        setTagSrcId(value);
        return this;
    }

    @Override
    public TagRecord values(String value1, UUID value2, UUID value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagRecord
     */
    public TagRecord() {
        super(Tag.TAG);
    }

    /**
     * Create a detached, initialised TagRecord
     */
    public TagRecord(String value, UUID id, UUID tagSrcId) {
        super(Tag.TAG);

        setValue(value);
        setId(id);
        setTagSrcId(tagSrcId);
    }
}
