/*
 * This file is generated by jOOQ.
 */
package place.sita.labelle.jooq.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;

import place.sita.labelle.jooq.tables.TaskPlanning;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskPlanningRecord extends TableRecordImpl<TaskPlanningRecord> implements Record4<UUID, UUID, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.task_planning.task_type_id</code>.
     */
    public void setTaskTypeId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.task_planning.task_type_id</code>.
     */
    public UUID getTaskTypeId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.task_planning.id</code>.
     */
    public void setId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.task_planning.id</code>.
     */
    public UUID getId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.task_planning.config</code>.
     */
    public void setConfig(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.task_planning.config</code>.
     */
    public String getConfig() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.task_planning.creation_date</code>.
     */
    public void setCreationDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.task_planning.creation_date</code>.
     */
    public LocalDateTime getCreationDate() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, UUID, String, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UUID, UUID, String, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return TaskPlanning.TASK_PLANNING.TASK_TYPE_ID;
    }

    @Override
    public Field<UUID> field2() {
        return TaskPlanning.TASK_PLANNING.ID;
    }

    @Override
    public Field<String> field3() {
        return TaskPlanning.TASK_PLANNING.CONFIG;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return TaskPlanning.TASK_PLANNING.CREATION_DATE;
    }

    @Override
    public UUID component1() {
        return getTaskTypeId();
    }

    @Override
    public UUID component2() {
        return getId();
    }

    @Override
    public String component3() {
        return getConfig();
    }

    @Override
    public LocalDateTime component4() {
        return getCreationDate();
    }

    @Override
    public UUID value1() {
        return getTaskTypeId();
    }

    @Override
    public UUID value2() {
        return getId();
    }

    @Override
    public String value3() {
        return getConfig();
    }

    @Override
    public LocalDateTime value4() {
        return getCreationDate();
    }

    @Override
    public TaskPlanningRecord value1(UUID value) {
        setTaskTypeId(value);
        return this;
    }

    @Override
    public TaskPlanningRecord value2(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public TaskPlanningRecord value3(String value) {
        setConfig(value);
        return this;
    }

    @Override
    public TaskPlanningRecord value4(LocalDateTime value) {
        setCreationDate(value);
        return this;
    }

    @Override
    public TaskPlanningRecord values(UUID value1, UUID value2, String value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TaskPlanningRecord
     */
    public TaskPlanningRecord() {
        super(TaskPlanning.TASK_PLANNING);
    }

    /**
     * Create a detached, initialised TaskPlanningRecord
     */
    public TaskPlanningRecord(UUID taskTypeId, UUID id, String config, LocalDateTime creationDate) {
        super(TaskPlanning.TASK_PLANNING);

        setTaskTypeId(taskTypeId);
        setId(id);
        setConfig(config);
        setCreationDate(creationDate);
    }
}
